version: '3'
services:
  db:
    image: mysql:8
    ports: 
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: suite340root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: suite340
    networks:
      - dbadmin

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    environment: 
      PMA_HOST: db
    networks:
      - dbadmin

  volumes:
    db_data:
  networks:
    dbadmin