version: '3.3'
services:
  apache:
    build: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/ 
    restart: always
    ports:
      - 80:80
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql/
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: suite340root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      -  8080:80
    environment:
      PMA_HOST: db
