version: '3.3'
services:
  php-back:
    build: 
      dockerfile: ./php-back/Dockerfile
      context: .
    depends_on:
      - db
    volumes:
      - ./php-back/:/var/www/html
    restart: always
    ports:
      - 80:80
    networks:
      - net
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql/
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feis_link
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      -  8081:80
    environment:
      PMA_HOST: db
    networks:
      - net

  node:
    depends_on: 
      - db
    build:
      dockerfile: ./node-back/Dockerfile
      context: .
    restart: always
    ports: 
      - 81:3000
    volumes: 
      - ./node-back/:/usr/src/app
    networks:
      - net

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - net

networks:
  net: